# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e33a32e44af24fb96cb2497da8d7277163a5cdc9ab5401549ddea9f999db07ef41fa4b69a83fad8b973430da4ad06ebe559dfcc5f8ec74b67dea676473bf0c84

test:
  secret_key_base: 9dd1dd0444f48ca620a07aab1d7aa2353d94b7a4d209abe5f94cfaa93af8eec2a5f4f9f20d32e67a05125bcfc666614f24b55421cba9a0d12fa957002e5e867c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
